app_name: Agentic-Evals
version: 1.0.0
data_generation:
  input_path: datasets
  input_file: queries.txt
  output_path: datasets
  output_file: agent_function_call.json
pipeline:
  steps:
    - data_generation
    - data_transformation
    - evaluation
    - reporting
logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
